### ISSUE TITLE
Handling usual pushes.

### ISSUE THREAD

**Issue by Roman-Markov** [yandexmobile/metrica-push-sdk-android#14]
Hello, as I see according to docs currently we can receive and handle only silent pushes. Is any way to receive and process usual pushes?

**Comment by NesterovichAlexey** [comment]
Hello.
Usual pushes are processed only SDK. Application can get payload after clicking on push.

**Comment by Roman-Markov** [comment]
Ok, thank you, but I need some clarifications

Do you mean AppMetrica Push SDK, Firebase SDK or Android SDK?

Notifications which appears when we send NOT silent pushes are not built by us in specific receivers or services. But, probably, AppMetrica Push SDK. Hence how can we get payload from it?

**Comment by Roman-Markov** [comment]
Ok, thank you very mush!
