### ISSUE TITLE
Токен устройства не соответствует приложению

### ISSUE THREAD

**Issue by CoolMind** [yandexmobile/metrica-push-sdk-android#15]
Hello!

I added Push support and want to test a push campaign. After I added test device, I sent push and didn't receive it (0/0). I learnt that I should check tokens actualization as in https://appmetrica.yandex.ru/blog/push-token-update. A checkbox in settings was set.
When I tested my device with Silent push, i got: "Токен устройства не соответствует приложению". If I created a test device with fake GAID, I got: "Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK".
How to actualize a token?

**Comment by NesterovichAlexey** [comment]
Hi. 
How you initialized Push SDK? Via google-services.json or via AndroidManifest?
In most cases, identifiers(app_id and sender_id)  specified in the application or [server key](https://appmetrica.yandex.ru/docs/mobile-sdk-dg/push/android-settings.html) specified in AppMetrica web interface are incorrect or do not correspond to each other.

**Comment by CoolMind** [comment]
@NesterovichAlexey, hello!

Thanks for your support!
I have `google-services.json` received from Firebase. There I have 2 `package_name`s (for release and debug). In AndroidManifest I have `android:name=".MyApplication"`, `MyFirebaseMessagingService` service, `SilentPushReceiver`. In `MyApplication` I wrote these lines in `onCreate()`:

        // Создание расширенной конфигурации библиотеки.
        val config = YandexMetricaConfig.newConfigBuilder(appMetricaApiKey).build()
        // Инициализация AppMetrica SDK.
        YandexMetrica.activate(applicationContext, config)
        // Автоматическое отслеживание активности пользователей.
        YandexMetrica.enableActivityAutoTracking(this)
        // Push-уведомления.
        YandexMetricaPush.init(applicationContext)

I didn't find app_id and sender_id in the application.

**Comment by NesterovichAlexey** [comment]
> If Ключ сервера in AppMetrica is incorrect, can I delete and add it again so that not to waste Android audience? I mean won't it change API key (для использования в SDK)?

Yes. But you need have access rights read/edit.
![image](https://user-images.githubusercontent.com/25264806/55572343-0b2b6f80-5710-11e9-9dac-66dd51f56987.png)

**Comment by CoolMind** [comment]
@NesterovichAlexey, yes, I have these rights. I can check Firebase again and paste from there.

**Comment by CoolMind** [comment]
@NesterovichAlexey, thank you very much!
