### ISSUE TITLE
Blank push messages

### ISSUE THREAD

**Issue by CoolMind** [yandexmobile/metrica-push-sdk-android#16]
Hello!

I found that push notifications may contain an icon with empty title and body. If you have a Firebase service from https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService, you will get blank messages.
Please, update a documentation to describe this situation. It wasted much time for me to recognize this.

Also, please update the documentation about a recever. What `exported` value will it have?

![Screenshot_33](https://user-images.githubusercontent.com/10630436/55613831-4b343600-5794-11e9-8ad9-20fa1d7625df.png)

**Comment by NesterovichAlexey** [comment]
Hi!
> What `exported` value will it have?

`exported` must be `false`

> I found that push notifications may contain an icon with empty title and body.

Can you tell me more about it? How do you send a push? What parameters?

**Comment by CoolMind** [comment]
Thanks for `exported`!

> Can you tell me more about it? How do you send a push? What parameters?

**1.** I create push campaign as usual. Name it, select a segment (choose only newer version that doesn't exist in Play Market to avoid a wider user coverage). 

![Screenshot_34](https://user-images.githubusercontent.com/10630436/55623286-3c0cb280-57ab-11e9-9416-c2dfc0bb3eb0.png)

**2.** Fill a title and a body of the notification.

![Screenshot_35](https://user-images.githubusercontent.com/10630436/55623393-8aba4c80-57ab-11e9-9800-925d2b0d9dfd.png)

**3.** Finally I get a result and send notifications.

![Screenshot_36](https://user-images.githubusercontent.com/10630436/55623525-eab0f300-57ab-11e9-8c00-1319f02ea970.png)

In case I have this service in `AndroidManifest`:
```
        <service
            android:name=".presentation.MyFirebaseMessagingService"
            android:permission="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

and send from AppMetrica, I get empty title and body, but with white icon (2 colors only are used).

If I send from FCM, push contains a color icon and title, body.

If I remove this service from Manifest, FCM keeps on sending normal pushes, but AppMetrica sends correct title and body with different icon. It is colourful, but like a launcher icon inside a circle.

**Comment by NesterovichAlexey** [comment]
You invoke `new MetricaMessagingService().processPush(this, message);` when push come to `MyFirebaseMessagingService`?
https://appmetrica.yandex.com/docs/mobile-sdk-dg/push/android-other-push-services-settings.html

AppMertica Push SDK not show push with empty title and body. Perhaps push is handled by firebase.

**Comment by CoolMind** [comment]
@NesterovichAlexey, thank you!

> You invoke new MetricaMessagingService().processPush(this, message); when push come to MyFirebaseMessagingService?

Sorry, I forgot it.

I followed https://tech.yandex.ru/appmetrica/doc/mobile-sdk-dg/push/android-other-push-services-settings-docpage/ and set so:

```
        <service
            android:name=".presentation.MyFirebaseMessagingService"
            android:enabled="true"
            android:exported="false">
            <intent-filter android:priority="100">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service
            android:name="com.yandex.metrica.push.firebase.MetricaMessagingService"
            tools:node="remove" />
```
In `MyFirebaseMessagingService` added lines as you offered:

```
         // AppMetrica автоматически распознает свои сообщения и обработает только их.
         MetricaMessagingService().processPush(this, remoteMessage)
``` 

Currently I have this:

```
class MyFirebaseMessagingService : FirebaseMessagingService() {

    private lateinit var settingsInteractor: SettingsInteractor


    override fun onCreate() {
        super.onCreate()

        settingsInteractor = SettingsInteractorImpl(this)
    }


    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)

        // AppMetrica автоматически распознает свои сообщения и обработает только их.
        MetricaMessagingService().processPush(this, remoteMessage)

        // Реализуйте логику отправки сообщений в другие SDK.
        val notificationBuilder = NotificationCompat.Builder(this@MyFirebaseMessagingService,
            getString(R.string.default_notification_channel_id))
            .setContentTitle(remoteMessage.notification?.title ?: "")
            .setContentText(remoteMessage.notification?.body ?: "")
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setStyle(NotificationCompat.BigTextStyle())
            .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
            .setSmallIcon(R.drawable.ic_notification_icon)
            .setAutoCancel(true)

        val notificationManager: NotificationManager =
            getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        // Create pending intent, mention the Activity which needs to be triggered
        // when user clicks on notification.
        val intent = Intent(this, OnboardingActivity::class.java)
        val pendingIntent = PendingIntent.getActivity(this, 0, intent,
            PendingIntent.FLAG_UPDATE_CURRENT)
        notificationBuilder.setContentIntent(pendingIntent)

        // Since android Oreo notification channel is needed.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channelId = getString(R.string.default_notification_channel_id)
            val channel =
                NotificationChannel(channelId, "title",
                    NotificationManager.IMPORTANCE_DEFAULT).apply {
                    description = "body"
                    enableLights(true)
                    enableVibration(true)
                    lightColor = Color.CYAN
                    lockscreenVisibility = Notification.VISIBILITY_PUBLIC
                    canShowBadge()
                    setShowBadge(true)
                }
            notificationManager.createNotificationChannel(channel)
            notificationBuilder.setChannelId(channelId)
        }

        val notification = notificationBuilder.build()
        notificationManager.notify(NOTIFICATION_ID, notification)
    }

    /**
     * Called if InstanceID token is updated. This may occur if the security of
     * the previous token had been compromised. Note that this is called when the InstanceID token
     * is initially generated so this is where you would retrieve the token.
     */
    override fun onNewToken(token: String?) {
        super.onNewToken(token)

        // If you want to send messages to this application instance or
        // manage this apps subscriptions on the server side, send the
        // Instance ID token to your app server.
//        sendRegistrationToServer(token)

        settingsInteractor.setPushToken(token)
    }


    companion object {
        private const val NOTIFICATION_ID = 1
    }
}
```

Now I have these two notifications on one device after sending push from AppMetrica. A launcher icon and a white icon with empty body.

![87](https://user-images.githubusercontent.com/10630436/55627329-952e1380-57b6-11e9-8066-95687fd4d4c7.png)

If I send from Firebase, I will get other notification:

![86](https://user-images.githubusercontent.com/10630436/55627430-d6bebe80-57b6-11e9-9430-55fb03a4b713.png)

**Comment by CoolMind** [comment]
Probably I understood a problem. Instead of sending push to Firebase I try to show it.

**Comment by NesterovichAlexey** [comment]
This is happening because push is processed and AppMetrica Push SDK, and your handler.
You can add `remoteMessage.data.containsKey("yamp")` to check that push from Metrica.
```kt
...
override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)

        // Метрика умеет распозновать свои уведомления,
        // но т.к. все равно надо проверять чей пуш, чтобы самим не обработать метричный пуш,
        // то можно лишний раз не дергаеть Метрику.
        if (remoteMessage.data.containsKey("yamp")) {
            MetricaMessagingService().processPush(this, remoteMessage)
            return
        }

        // Реализуйте логику отправки сообщений в другие SDK.
        val notificationBuilder = NotificationCompat.Builder(this@MyFirebaseMessagingService,
                getString(R.string.default_notification_channel_id))
                .setContentTitle(remoteMessage.notification?.title ?: "")
                .setContentText(remoteMessage.notification?.body ?: "")
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .setStyle(NotificationCompat.BigTextStyle())
                .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                .setSmallIcon(R.drawable.ic_notification_icon)
                .setAutoCancel(true)
...
```

**Comment by CoolMind** [comment]
@NesterovichAlexey, you are genious!

![89](https://user-images.githubusercontent.com/10630436/55629778-babe1b80-57bc-11e9-8ae0-27ef0a09ab16.png)

Please, update a documentation, if it is needed.

**Comment by NesterovichAlexey** [comment]
> Also, should we save a token in SharedPreferences?

It makes no sense to save the token in SharedPreferences. It makes sense to send it to your server if from it you will send pushes in the application.

**Comment by CoolMind** [comment]
> 
> 
> Hi!
> 
> > What `exported` value will it have?
> 
> `exported` must be `false`
> 
> > I found that push notifications may contain an icon with empty title and body.
> 
> Can you tell me more about it? How do you send a push? What parameters?

After several months I found that `onReceive` in `SilentPushReceiver` was not called in case of silent push message.

So, `android:exported` must be "true" in `AndroidManifest` (see https://appmetrica.yandex.ru/docs/mobile-sdk-dg/push/android-initialize.html#settings-of-silent-push):

        <receiver
            android:name=".SilentPushReceiver"
            android:exported="true"
            >
            <intent-filter>
                
                <action android:name="${applicationId}.action.ymp.SILENT_PUSH_RECEIVE" />
            </intent-filter>
        </receiver>
