### ISSUE TITLE
Push-notifications don't work on Xiaomi device (MIUI, Android API 27)

### ISSUE THREAD

**Issue by Ringo-Freek** [yandexmobile/metrica-push-sdk-android#17]
Push-notifications don't come through when the app is closed. But if I turn on settings of the app ("autostart" in "permissions" and "no restrictions" in "battery saver") then notifications show up well. 
Although there are some apps (e.g. AliExpress) on the device that work well even they are closed without settings.
 
Could tell me how to resolve the problem?

mobmetricapushlib 1.3.0
mobmetricalib 3.5.3

**Comment by NesterovichAlexey** [comment]
Firebase is responsible for delivering push notifications to the device. The Push SDK receives the push from firebase, processes and displays it.
It seems AliExpress is showing a normal notification instead of a push-notification.

**Comment by Ringo-Freek** [comment]
> Firebase is responsible for delivering push notifications to the device. The Push SDK receives the push from firebase, processes and displays it.
> It seems AliExpress is showing a normal notification instead of a push-notification.

@NesterovichAlexey
Do I understand you correctly, is it necessary to use Firebase instead of Metrica Push SDK to solve the problem?

**Comment by NesterovichAlexey** [comment]
No. Firebase will have the same problems. Because the push SDK uses Firebase as a way to deliver push-notifications.

**Comment by Ringo-Freek** [comment]
> No. Firebase will have the same problems. Because the push SDK uses Firebase as a way to deliver push-notifications.

And I have another app where the push-notifications are implemented via Firebase, but there are no problems with displaying them.

**Comment by Wannaaskaquestion** [comment]
@NesterovichAlexey @Ringo-Freek 
Hi there, I've the same problem (push-notifications don't come when the app is killed, but they do when the app is often used and after 1-2 days they don't arrive again)
If I turn on the settings as @Ringo-Freek said, then push-notifications arrive without any problems
I haven't had such problems with other apps where push-notifications are received via firebase directly

**Comment by CoolMind** [comment]
I don't have these cheap and buggy devices with advertisements called Xiaomi, but want to ask whether https://stackoverflow.com/questions/30748107/xiaomi-does-not-receive-notification-when-application-is-not-running, https://c.mi.com/thread-1545043-1-0.html could help. Also what push notifications do you use? Do they contain data, big picture?
