### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by calmmycode** [yandexmobile/metrica-push-sdk-android#22]
In docs we need to add this:
`implementation "com.android.support:support-compat:28.0.0"`
but we should migrate to androidX

**Comment by NesterovichAlexey** [comment]
Hi.
You can use the AppMetrica Push SDK with AndroidX. You need to add `android.enableJetifier=true` in your `gradle.properties` file.
https://developer.android.com/jetpack/androidx/migrate?hl=ru#migrate_an_existing_project_using_android_studio
