### ISSUE TITLE
Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK

### ISSUE THREAD

**Issue by hansandroid** [yandexmobile/metrica-push-sdk-android#25]
Hello!

I added Hms Push support and want to test a push campaign. When I tested my application on huawei cloud device with push, i got: "Для тестового устройства отсутствует токен, установите на тестовом устройстве и запустите приложение с интегрированным AppMetrica Push SDK". I have some build flavors and build types of application, i test all of them and for all appids and appsecrets i have same error message.
How to actualize a token?

**Comment by NesterovichAlexey** [comment]
Hi!
There are several possible options for what could have gone wrong. Some of them may require contacting our support. It may take some time, so there are few things you could check first:
try to get token directly from HMS without AppMetrica Push SDK. [Here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/android-client-dev-0000001050042041-V5#EN-US_TOPIC_0000001078601368__section11455525765) are some examples how to do it. In case of error in HMS Push SDK integration you will get an error (it could be some issues with your test app certificate fingerprint and etc).
If everything is ok, please make sure that you choose correct identifier type in your AppMetrica Push SDK console (it matches the passed id type).
If you will stay have issues with push sending please contact our support team via this form:
https://appmetrica.yandex.com/docs/troubleshooting/other.html

**Comment by hansandroid** [comment]
Thanks for answer but In my case everything is correct. I asked a question in the feedback form.
