### ISSUE TITLE
Alerting уведомления

### ISSUE THREAD

**Issue by yanushok** [yandexmobile/metrica-push-sdk-android#28]
Здравствуйте. По умолчанию при установке приложения пуш уведомления работают в режиме silent (по крайней мере так называется настройка уведомлений в эмуляторе), на реальном девайсе это "умные уведомления" без звука, баннера и т.д. Т.е. пользователь может увидеть его только при ручном смахивании шторки.
Можно ли как-то изменить это поведение, чтобы не приходилось лезть руками в настройки приложения и менять политику уведомлений?

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 13023667. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp06.06.2021, 23:34, "Yan Yunitski" ***@***.***>:
Здравствуйте. По умолчанию при установке приложения пуш уведомления работают в режиме silent (по крайней мере так называется настройка уведомлений в эмуляторе), на реальном девайсе это "умные уведомления" без звука, баннера и т.д. Т.е. пользователь может увидеть его только при ручном смахивании шторки.
Можно ли как-то изменить это поведение, чтобы не приходилось лезть руками в настройки приложения и менять политику уведомлений?

**Comment by akbarpulatov** [comment]
Есть новости? @yanushok как решили проблему?

**Comment by akbarpulatov** [comment]
У меня тоже такая же фигня пуши летят как сайлент

**Comment by yanushok** [comment]
> Есть новости? @yanushok как решили проблему?

Не решили)

**Comment by ghost** [comment]
Добрый день!

Поменять описанное вами поведение можно 2-я способами:

1. Через метод [[YandexMetricaPush.getDefaultNotificationChannel](https://appmetrica.yandex.ru/docs/mobile-sdk-dg/push/android/ref/YandexMetricaPush.html#method_detail__method_getDefaultNotificationChannel)]

Этот вариант подойдет, если тестирования проводилось не в продовой версии приложения.

Метод возвращает дефолтный канал уведомлений, который используется PushSDK для отображения пуш-уведомлений. 
Далее задать для него настройки с помощью методов [[NotificationChannel](https://developer.android.com/reference/android/app/NotificationChannel)]

2.  Создать свой канал для пуш-уведомлений: https://developer.android.com/training/notify-user/channels
При создании пуш-кампании, в "Дополнительных настройках" указать id в поле "Канал", созданный по инструкции выше.
