### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate receiver com.google.android.gms.gcm.GcmReceiver

### ISSUE THREAD

**Issue by Verichev** [yandexmobile/metrica-push-sdk-android#5]
The library doesn't work with newest firebase implementation.

After sending broadcast notification to devices I get crash:
java.lang.RuntimeException: Unable to instantiate receiver com.google.android.gms.gcm.GcmReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmReceiver" on path: DexPathList[[zip file "/data/app/com.gpn.azs-2/base.apk"],nativeLibraryDirectories=[/data/app/com.gpn.azs-2/lib/arm64, /system/lib64, /vendor/lib64]]

**Comment by NesterovichAlexey** [comment]
The old version of the library uses gcm and requires a dependency on `com.google.android.gms: play-services-gcm`. Version 1.0.0 is already using firebase. If you need firebase, use version 1.0.0 or higher
