### ISSUE TITLE
Android api 27 problems

### ISSUE THREAD

**Issue by OJIer3** [yandexmobile/metrica-push-sdk-android#9]
v 0.6.1 after updating app compileSdkVersion and targetSdkVersion to 27, and appcompat lib to v27 application stop receiving pushes.

**Comment by NesterovichAlexey** [comment]
It library recognizes the version of the support library from the metadata in the manifest. Early support library added to the version in the manifest itself, but she stopped doing it in v27. You can add the version of the support library in the manifest:
<meta-data android:name="android.support.VERSION" android:value="SUPPORT_VERSION" />
SUPPORT_VERSION - version of the support library you are using. For example, "27.0.2".

We will think about what else can be done.

**Comment by NesterovichAlexey** [comment]
In version 1.0.0 this problem has been fixed and you no longer need to add the support library version to the manifest.
